/*
    ESTRUCTURA DE CONTROL CASE
    
    SIMPLE CASE
    
    
*/

/*
    A -> ELECTRONICA
    B -> INFORMATICA
    C -> MANTENIMIENTO
    D -> ADMINISTRACION
    
*/

SET SERVEROUTPUT ON;

DECLARE
    DEPTO CHAR(1);
BEGIN
    DEPTO:='Z';
    
    CASE DEPTO -- <- EVALUA EL VALOR QUE TENGA "DEPTO"
        WHEN 'A' THEN DBMS_OUTPUT.PUT_LINE('DEPTO DE ELECTRONICA'); -- CUANDO SEA 'A' ENTONCES ----....
        WHEN 'B' THEN DBMS_OUTPUT.PUT_LINE('DEPTO DE INFORMATICA'); -- CUANDO SEA 'B' ENTONCES ....
        WHEN 'C' THEN DBMS_OUTPUT.PUT_LINE('DEPTO DE MANTENIMIENTO'); -- CUANDO SEA 'C' ENTONCES ...
        WHEN 'D' THEN DBMS_OUTPUT.PUT_LINE('DEPTO DE ADMINISTRACION'); -- CUJANDO SEA 'D' ENTONCES ....
        ELSE DBMS_OUTPUT.PUT_LINE('EL DEPARTAMENTO PROPORCIONADO NO EXISTE');
    END CASE;
END;