-- PRACTICE VARIABLES 1. CREATE TWO VARIABLES AND DISPLAY THE SUM OF THOSE.


SET SERVEROUTPUT ON

DECLARE
    NUM_1 NUMBER;
    NUM_2 NUMBER;
    RES NUMBER;
BEGIN
    NUM_1:=10;
    NUM_2:=20;
    RES:=NUM_1+NUM_2;
    
    DBMS_OUTPUT.PUT_LINE(''||RES);
END;