SET SERVEROUTPUT ON

/***
**
** USO DE FUNCIONES SQL DENTRO DE PLSQL
**
***/

DECLARE
    NOMBRE VARCHAR2(100);
    PRIMER_NOMBRE NOMBRE%TYPE;
    SEGUNDO_NOMBRE PRIMER_NOMBRE%TYPE;
BEGIN
    NOMBRE:='ALFONSO HERNANDEZ';
    PRIMER_NOMBRE:=SUBSTR(NOMBRE,0,7);
    SEGUNDO_NOMBRE:=TRIM(SUBSTR(NOMBRE,LENGTH(PRIMER_NOMBRE)+1,LENGTH(NOMBRE)-1));
    
    DBMS_OUTPUT.PUT_LINE(NOMBRE);
    DBMS_OUTPUT.PUT_LINE(PRIMER_NOMBRE);
    DBMS_OUTPUT.PUT_LINE(SEGUNDO_NOMBRE);
END;