/*
** PRACTICA 1 ESTRUCTURA IF ELSE ELSIF **

- DEBEMOS HACER UN BLOQUE PL/SQL ANONIMO, DONDE DECLARAREMOS UNA VARIABLE NUMBER Y LE PONDREMOS ALGUN VALOR
- DEBE INDICAR SI EL NUMERO ES PAR O IMPAR, USANDO IF...ELSE
- COMO PISTA, RECORDEMOS QUE PODEMOS UTILIZAR LA FUNCION "MOD" QUE PERMITE ADIVIDAR EL MODULO DE UNA DIVISION(RESIDUO) EJ: MOD(10,4) -> RESIDUO DE 10/4


*/

SET SERVEROUTPUT ON

-- BLOQUE PLSQL
DECLARE
    NUMERO NUMBER:=3;
BEGIN

    IF MOD(NUMERO,2)=0 THEN
        DBMS_OUTPUT.PUT_LINE('NUMERO PAR');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NUMERO IMPAR');
    END IF;
END;


/*
** PRACTICA 2 ESTRUCTURA IF ELSE ELSIF **

- Crea una variable CHAR(1) denominada TIPO_PRODUCTO
- Establecer un valor entre "A" y "E".
- Visualizar el siguiente resultado

o 'A' --> Electronica
o 'B' --> Informática
o 'C' --> Ropa
o 'D' --> Música
o 'E' --> Libros

Cualquier otro valor debe visualizar "El código es incorrecto"

*/

DECLARE
    TIPO_PRODUCTO CHAR(1):='A';
BEGIN
    IF UPPER(TIPO_PRODUCTO)='A' THEN
        DBMS_OUTPUT.PUT_LINE('ELECTRONICA');
    ELSIF TIPO_PRODUCTO='B' THEN
        DBMS_OUTPUT.PUT_LINE('INFORMATICA');
    ELSIF TIPO_PRODUCTO='C' THEN
        DBMS_OUTPUT.PUT_LINE('ROPA');
    ELSIF TIPO_PRODUCTO='D' THEN
        DBMS_OUTPUT.PUT_LINE('MUSICA');
    ELSIF TIPO_PRODUCTO='E' THEN
        DBMS_OUTPUT.PUT_LINE('LIBROS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EL CODIGO ES INCORRECTO!!');
    END IF;
END;
